export const DATA = {
    India: "New Delhi",
    "United States": "Washington, D.C.",
    France: "Paris",
    Germany: "Berlin",
    Canada: "Ottawa",
    Australia: "Canberra",
    Brazil: "Brasília",
    Japan: "Tokyo",
    China: "Beijing",
    Russia: "Moscow",
    "United Kingdom": "London",
    "South Africa": "Pretoria",
    Mexico: "Mexico City",
    Italy: "Rome",
    Spain: "Madrid",
    "Saudi Arabia": "Riyadh",
    "South Korea": "Seoul",
    Argentina: "Buenos Aires",
    Egypt: "Cairo",
    Turkey: "Ankara",
};
